### ISSUE TITLE
Capston II review

### ISSUE THREAD

**Issue by Mar12358** [Mar12358/JavaScriptCapstone#21]
**Link to Kanban Project Board:** https://github.com/Mar12358/JavaScriptCapstone/projects/2

We are 2 people on the team for this capstone project.
@Mar12358 and @AliShahSafdari

**Comment by levy002** [comment]
## Hello @Team  , :wave:
### I'm Levy, your PR reviewer

Good job so far :+1: 
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif)

## Status: REQUIRED CHANGES ♻️
_Check the comments under the review._

- [ ] Kindly make sure to assign the task cards to the team members, so we should see a circle with the user's avatar on each card. See the example below:

     - ### EXAMPLE OF INDIVIDUAL TASK
     
     ![image](https://github.com/nilab-khwaja/Js-Capstone/assets/87197412/f347308e-8d5b-4b40-a5ee-4a24c94da9af)

     - ### EXAMPLE OF GROUP TASK
     
    ![image](https://github.com/nilab-khwaja/Js-Capstone/assets/87197412/1fabb880-e078-48b5-91b0-3ea4c89ea0b7)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @levy002 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Mar12358** [comment]
Thanks for the review! 
Changes made,
Cheers!

**Comment by divinecharlotte** [comment]
# Hello @Team    😃 🥳 🎉 🎈 

Great Job 😄 👏 You've done it. Your project is complete!  There is nothing else to say  👍🏻 ✅ 
### To Highlight 💯

- Descriptive issue👍 
- Good communication with the reviewer 👍 
 




## Congratulations! 🎉 

<img src="https://media3.giphy.com/media/3KC2jD2QcBOSc/giphy.gif"/>

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
